import pytest
from unittest.mock import patch, MagicMock
from src.core.state import BackportState, PatchClassification, PatchType
from src.agents.agent1_classifier import classify_patch, is_auto_generated_file

def test_is_auto_generated_file():
    content_with_lombok = "@Generated\npublic class GeneratedClass {}"
    content_with_jooq = "This file is generated by jOOQ."
    content_normal = "public class NormalClass {}"
    
    assert is_auto_generated_file(content_with_lombok) is True
    assert is_auto_generated_file(content_with_jooq) is True
    assert is_auto_generated_file(content_normal) is False

@patch("src.agents.agent1_classifier.get_default_router")
def test_classify_patch_type_i(mock_get_router):
    mock_model = MagicMock()
    mock_get_router.return_value.get_model.return_value = mock_model
    
    mock_model.with_structured_output.return_value.invoke.return_value = PatchClassification(
        patch_type=PatchType.TYPE_I,
        confidence=0.95,
        token_budget_estimate=1000,
        reasoning="Simple exact match string replacement",
        is_auto_generated=False
    )
    
    state = BackportState(
        patch_content="--- a/src/main.java\n+++ b/src/main.java\n- old_code\n+ new_code\n",
        target_repo_path="/path/to/repo",
        target_branch="6.x",
        worktree_path=None,
        clean_state=True,
        classification=None,
        localization_results=[],
        hunks=[],
        retry_contexts=[],
        current_attempt=1,
        max_retries=3,
        tokens_used=0,
        wall_clock_time=0.0,
        status="started"
    )
    
    new_state = classify_patch(state)
    
    assert new_state["classification"] is not None
    assert new_state["classification"].patch_type == PatchType.TYPE_I
    assert new_state["classification"].confidence == 0.95

