import re
from typing import Dict, Any
from src.core.state import BackportState, PatchClassification, PatchType
from src.core.llm_router import get_default_router, LLMTier

def is_auto_generated_file(content: str) -> bool:
    """
    Check if a file content looks like it was auto-generated.
    Looks for @Generated, MapStruct, jOOQ, Thrift, OpenAPI, etc.
    """
    patterns = [
        r"@Generated",
        r"This file is generated by jOOQ",
        r"Generated by the protocol buffer compiler",
        r"Autogenerated by Thrift Compiler",
        r"Generated by the OpenAPI Generator"
    ]
    
    # Check only the first 30 lines for performance
    lines = content.splitlines()[:30]
    first_lines = "\n".join(lines)
    
    for pattern in patterns:
        if re.search(pattern, first_lines, re.IGNORECASE):
            return True
            
    return False

def classify_patch(state: BackportState) -> BackportState:
    """
    Agent 1: Patch Classifier
    Classifies the patch/hunks (TYPE I-V), assigns confidence, and estimates token budgets.
    Uses unified diff, commit msg, and PatchKnowledgeIndex.
    """
    patch_content = state["patch_content"]
    
    # LLM classification
    router = get_default_router()
    fast_model = router.get_model(LLMTier.FAST)
    
    # We use LangChain's structured output
    structured_llm = fast_model.with_structured_output(PatchClassification)
    
    prompt = f"""You are a specialized Patch Classifier for the OmniPort backporting system.
Analyze the following git unified diff and classify the complexity of the backport.

Classification Types:
- TYPE_I: Exact match string replacement, trivial backport.
- TYPE_II: Whitespace/formatting drift, requires fuzzy matching.
- TYPE_III: Structural changes, renamed methods, moved methods.
- TYPE_IV: Deep structural refactoring, significant API divergence.
- TYPE_V: Complete redesign, fundamentally different implementation.
- MIXED: Different hunks have different complexities.

Assess the confidence (0.0 to 1.0) and estimate the token budget required to resolve this patch.

Patch:
{patch_content}
"""

    classification_result = structured_llm.invoke(prompt)
    
    # Check if the target file is auto-generated based on the patch content additions
    # (In a real system we'd check the target file content directly if possible)
    is_auto_generated = is_auto_generated_file(patch_content)
    if is_auto_generated:
        classification_result.is_auto_generated = True
        
    state["classification"] = classification_result
    
    return state
