import re


def is_auto_generated_file(content: str) -> bool:
    """
    Check if a file content looks like it was auto-generated.
    Looks for @Generated, MapStruct, jOOQ, Thrift, OpenAPI, etc.
    """
    patterns = [
        r"@Generated",
        r"This file is generated by jOOQ",
        r"Generated by the protocol buffer compiler",
        r"Autogenerated by Thrift Compiler",
        r"Generated by the OpenAPI Generator",
    ]

    # Check only the first 30 lines for performance
    lines = content.splitlines()[:30]
    first_lines = "\n".join(lines)

    for pattern in patterns:
        if re.search(pattern, first_lines, re.IGNORECASE):
            return True

    return False
